window.volumeServices=(()=>{
  const profiles=window.serviceProfiles;
  profiles.finance={
    overall:'결제·송금·계정 제한 조건 확인 필요',
    items:(n,terms,privacy)=>[
      ['payment','결제·송금','수수료와 환율이 거래마다 달라질 수 있음','high',`${n}의 송금·환전·투자에는 거래 방식, 국가, 결제수단과 자산 종류에 따라 수수료·환율·세금이 적용될 수 있습니다.`,`보내는 금액만 보고 진행하면 수수료와 환율 차이 때문에 상대가 받는 금액이나 실제 지출이 달라질 수 있습니다.`,terms],
      ['privacy','개인정보','신원·거래·기기 정보가 함께 처리됨','high',`${n}는 본인확인 정보, 계좌·카드, 거래 상대와 내역, 기기·접속 정보를 결제 처리, 사기 방지와 법적 의무 이행에 활용할 수 있습니다.`,`누구에게 언제 얼마를 보냈는지와 어떤 기기로 접속했는지가 금융 활동 기록으로 남을 수 있습니다.`,privacy],
      ['content','계정 권리','잔액은 예금과 보호 방식이 다를 수 있음','high',`${n}의 잔액·포인트·가상자산은 은행 예금과 법적 성격이나 보호 범위가 다를 수 있고 가치 변동 또는 이용 제한이 생길 수 있습니다.`,`앱에 보이는 돈이 항상 은행 예금처럼 보호되거나 언제든 같은 가치로 인출된다는 뜻은 아닙니다.`,terms],
      ['cancel','취소·환불','완료된 거래는 되돌리기 어려움','high',`송금·환전·투자 거래는 처리 단계에 따라 취소가 불가능하고, 잘못 보낸 거래의 회수는 상대방 동의나 별도 분쟁 절차가 필요할 수 있습니다.`,`받는 사람이나 금액을 잘못 확인하고 승인하면 고객센터에 연락해도 바로 되돌리지 못할 수 있습니다.`,terms],
      ['other','기타 주의','보안 판단으로 계정이 제한될 수 있음','high',`${n}는 이상 거래, 신원 확인 미완료 또는 법적 요청이 있으면 거래를 보류하고 계정을 제한하거나 추가 서류를 요구할 수 있습니다.`,`갑자기 송금이나 출금이 막힐 수 있으므로 큰 거래 전에는 인증 상태와 한도를 확인해야 합니다.`,terms]
    ]
  };
  profiles.dating={
    overall:'위치·프로필 공개·구독 조건 확인 필요',
    items:(n,terms,privacy)=>[
      ['payment','결제·구독','유료 기능이 자동 갱신될 수 있음','high',`${n}의 프리미엄 구독은 앱스토어 또는 웹 결제로 자동 갱신될 수 있고, 해지는 결제한 경로에서 별도로 해야 할 수 있습니다.`,`앱만 삭제하면 결제가 멈추지 않아 다음 결제일에 구독료가 다시 나갈 수 있습니다.`,terms],
      ['privacy','개인정보','위치·선호·대화 활동이 민감한 정보가 됨','high',`${n}는 위치, 프로필, 선호, 매칭·대화와 기기 정보를 추천, 안전, 분석과 광고에 활용할 수 있습니다.`,`누구를 좋아했고 어디에서 앱을 썼는지 같은 정보가 계정 활동과 연결될 수 있습니다.`,privacy],
      ['content','프로필 공개','사진과 소개가 다른 이용자에게 노출됨','high',`프로필 사진과 소개는 설정한 거리·연령·지역의 이용자에게 표시되고 캡처나 외부 공유를 완전히 막기 어렵습니다.`,`앱에서만 보일 거라 생각한 사진과 소개가 상대방의 캡처로 밖에 퍼질 수 있습니다.`,terms],
      ['cancel','해지·삭제','구독 해지와 계정 삭제가 다름','high',`유료 구독 취소, 프로필 숨김과 계정 삭제는 서로 다른 절차이며, 삭제 뒤에도 법적 의무나 안전 대응을 위해 일부 기록이 남을 수 있습니다.`,`계정을 지웠다고 생각해도 결제가 계속되거나 신고 대응용 기록이 일정 기간 보관될 수 있습니다.`,terms],
      ['other','안전 주의','본인확인 표시가 신원 보증은 아님','high',`${n}의 인증 표시나 자동 탐지는 상대방의 신원과 의도를 완전히 보증하지 않으며, 신고에 따라 계정 이용이 제한될 수 있습니다.`,`인증 배지가 있어도 송금이나 개인정보 제공은 피하고, 의심스러운 상대는 직접 차단·신고해야 합니다.`,terms]
    ]
  };
  profiles.health={
    overall:'건강 데이터·자동결제·의료 한계 확인 필요',
    items:(n,terms,privacy)=>[
      ['payment','결제·구독','체험 뒤 자동 갱신될 수 있음','high',`${n}의 코칭·운동·명상 구독은 체험 종료 뒤 자동 결제될 수 있고 앱스토어 결제는 해당 스토어에서 해지해야 합니다.`,`체험만 해보려다 종료일을 놓치면 월간이나 연간 요금이 청구될 수 있습니다.`,terms],
      ['privacy','개인정보','건강·운동·위치 기록은 민감할 수 있음','high',`${n}는 운동, 수면, 체중, 심박수, 위치와 기기 정보를 기능 제공, 분석과 맞춤화에 활용할 수 있습니다.`,`언제 어디서 운동했고 몸 상태가 어땠는지가 장기간 계정 기록으로 남을 수 있습니다.`,privacy],
      ['content','서비스 한계','의료 진단이나 응급 서비스를 대신하지 않음','high',`${n}의 측정값·추천·콘텐츠는 일반적인 정보이며 전문 의료진의 진단, 처방이나 응급 대응을 대신하지 않습니다.`,`앱의 수치가 정상이어도 몸이 이상하면 앱만 믿지 말고 의료기관에 확인해야 합니다.`,terms],
      ['cancel','해지·삭제','연동 기기와 데이터 삭제가 따로일 수 있음','mid',`계정 삭제와 웨어러블·건강 플랫폼 연동 해제는 별도 절차일 수 있고 백업이나 법적 의무 때문에 일부 데이터가 즉시 지워지지 않을 수 있습니다.`,`앱 계정을 지워도 Apple Health나 Google Health Connect 같은 연결과 기존 사본을 따로 정리해야 할 수 있습니다.`,privacy],
      ['other','기타 주의','공유 설정으로 활동 위치가 드러날 수 있음','high',`친구, 그룹, 공개 피드나 운동 경로 공유 설정에 따라 집·직장 주변 위치와 생활 패턴이 다른 사람에게 노출될 수 있습니다.`,`달리기 시작점과 종료점을 공개하면 자주 머무는 장소를 다른 사람이 짐작할 수 있습니다.`,terms]
    ]
  };

  const catalog=[
    ['whatsapp','WhatsApp','whatsapp.com',['왓츠앱'],'W','social','https://www.whatsapp.com/legal/terms-of-service','https://www.whatsapp.com/legal/privacy-policy'],
    ['messenger','Messenger','messenger.com',['페이스북 메신저'],'M','social','https://www.facebook.com/legal/terms','https://www.facebook.com/privacy/policy/'],
    ['wechat','WeChat','wechat.com',['위챗'],'W','social','https://www.wechat.com/en/service_terms.html','https://www.wechat.com/en/privacy_policy.html'],
    ['qq','QQ','im.qq.com',['큐큐'],'Q','social','https://www.tencent.com/en-us/statement.html','https://www.tencent.com/en-us/privacy-policy.html'],
    ['viber','Viber','viber.com',['바이버'],'V','social','https://www.viber.com/terms/viber-terms-use/','https://www.viber.com/terms/viber-privacy-policy/'],
    ['imo','imo','imo.im',['이모 메신저'],'i','social','https://imo.im/terms','https://imo.im/privacy'],
    ['meetup','Meetup','meetup.com',['밋업'],'M','social','https://www.meetup.com/terms/','https://www.meetup.com/privacy/'],
    ['vk','VK','vk.com',['브이케이'],'VK','social','https://vk.com/terms','https://vk.com/privacy'],
    ['okru','OK','ok.ru',['오드노클라스니키'],'OK','social','https://ok.ru/regulations','https://ok.ru/privacy'],
    ['truthsocial','Truth Social','truthsocial.com',['트루스소셜'],'TS','social','https://truthsocial.com/terms-of-service','https://truthsocial.com/privacy-policy'],
    ['parler','Parler','parler.com',['팔러'],'P','social','https://parler.com/terms-of-service','https://parler.com/privacy-policy'],
    ['gab','Gab','gab.com',['갭'],'G','social','https://gab.com/about/tos','https://gab.com/about/privacy'],
    ['lemmy','Lemmy','join-lemmy.org',['레미'],'L','social','https://join-lemmy.org/','https://join-lemmy.org/'],
    ['fivehundredpx','500px','500px.com',['오백픽셀'],'500','social','https://500px.com/terms','https://500px.com/privacy'],
    ['imgur','Imgur','imgur.com',['이미저'],'I','social','https://imgur.com/tos','https://imgur.com/privacy'],
    ['giphy','GIPHY','giphy.com',['기피'],'G','social','https://support.giphy.com/hc/en-us/articles/360020027752-GIPHY-Terms-of-Service','https://support.giphy.com/hc/en-us/articles/360032872931-GIPHY-Privacy-Policy'],
    ['dribbble','Dribbble','dribbble.com',['드리블'],'D','social','https://dribbble.com/terms','https://dribbble.com/privacy'],
    ['artstation','ArtStation','artstation.com',['아트스테이션'],'AS','social','https://www.artstation.com/tos','https://www.artstation.com/privacy'],
    ['patreon','Patreon','patreon.com',['패트리온'],'P','social','https://www.patreon.com/policy/legal','https://privacy.patreon.com/policies'],
    ['kofi','Ko-fi','ko-fi.com',['코파이'],'K','social','https://more.ko-fi.com/terms','https://more.ko-fi.com/privacy'],
    ['buymeacoffee','Buy Me a Coffee','buymeacoffee.com',['바이미어커피'],'B','social','https://www.buymeacoffee.com/terms','https://www.buymeacoffee.com/privacy-policy'],
    ['substack','Substack','substack.com',['서브스택'],'S','social','https://substack.com/tos','https://substack.com/privacy'],
    ['wordpress','WordPress.com','wordpress.com',['워드프레스'],'WP','social','https://wordpress.com/tos/','https://automattic.com/privacy/'],
    ['blogger','Blogger','blogger.com',['블로거'],'B','social','https://policies.google.com/terms','https://policies.google.com/privacy'],
    ['disqus','Disqus','disqus.com',['디스커스'],'D','social','https://help.disqus.com/en/articles/1717102-terms-of-service','https://help.disqus.com/en/articles/1717103-disqus-privacy-policy'],

    ['youtubemusic','YouTube Music','music.youtube.com',['유튜브뮤직'],'YM','stream','https://www.youtube.com/static?template=terms','https://policies.google.com/privacy'],
    ['pandora','Pandora','pandora.com',['판도라뮤직'],'P','stream','https://www.siriusxm.com/legal','https://www.siriusxm.com/privacy'],
    ['iheartradio','iHeartRadio','iheart.com',['아이하트라디오'],'iH','stream','https://www.iheart.com/terms/','https://www.iheart.com/privacy/'],
    ['tunein','TuneIn','tunein.com',['튠인'],'T','stream','https://tunein.com/policies/terms/','https://tunein.com/policies/privacy/'],
    ['plex','Plex','plex.tv',['플렉스'],'P','stream','https://www.plex.tv/about/privacy-legal/plex-terms-of-service/','https://www.plex.tv/about/privacy-legal/'],
    ['roku','Roku','roku.com',['로쿠'],'R','stream','https://docs.roku.com/published/userterms','https://docs.roku.com/published/userprivacypolicy'],
    ['tubi','Tubi','tubitv.com',['투비'],'T','stream','https://tubitv.com/static/terms','https://tubitv.com/static/privacy'],
    ['plutotv','Pluto TV','pluto.tv',['플루토티비'],'P','stream','https://privacy.paramount.com/policy','https://privacy.paramount.com/policy'],
    ['mubi','MUBI','mubi.com',['무비'],'M','stream','https://mubi.com/terms_of_service','https://mubi.com/privacy_policy'],
    ['criterion','Criterion Channel','criterionchannel.com',['크라이테리온 채널'],'CC','stream','https://www.criterionchannel.com/terms','https://www.criterionchannel.com/privacy'],
    ['discoveryplus','discovery+','discoveryplus.com',['디스커버리플러스'],'d+','stream','https://www.discoveryplus.com/terms','https://www.wbdprivacy.com/policycenter/b2c/'],
    ['espnplus','ESPN+','plus.espn.com',['이에스피엔플러스'],'E+','stream','https://disneytermsofuse.com/','https://privacy.thewaltdisneycompany.com/'],
    ['sling','Sling TV','sling.com',['슬링티비'],'S','stream','https://www.sling.com/terms-of-use','https://www.sling.com/privacy'],
    ['fubotv','Fubo','fubo.tv',['푸보'],'F','stream','https://www.fubo.tv/documents/terms','https://www.fubo.tv/documents/privacy-policy'],
    ['dazn','DAZN','dazn.com',['다즌'],'D','stream','https://www.dazn.com/en-US/help/articles/terms','https://www.dazn.com/en-US/help/articles/privacy'],
    ['soop','SOOP','sooplive.co.kr',['숲','아프리카티비'],'S','stream','https://www.sooplive.co.kr/policy/terms','https://www.sooplive.co.kr/policy/privacy'],
    ['chzzk','CHZZK','chzzk.naver.com',['치지직'],'C','stream','https://policy.naver.com/policy/service.html','https://policy.naver.com/policy/privacy.html'],
    ['kick','Kick','kick.com',['킥'],'K','stream','https://kick.com/terms-of-service','https://kick.com/privacy-policy'],
    ['storytel','Storytel','storytel.com',['스토리텔'],'S','stream','https://www.storytel.com/terms','https://www.storytel.com/privacy'],
    ['scribd','Everand','everand.com',['에버랜드','스크리브드'],'E','stream','https://support.scribd.com/hc/en-us/articles/210129326-Terms-of-Use','https://support.scribd.com/hc/en-us/articles/210129366-Privacy-Policy'],
    ['podbean','Podbean','podbean.com',['팟빈'],'P','stream','https://www.podbean.com/terms','https://www.podbean.com/privacy'],
    ['pocketcasts','Pocket Casts','pocketcasts.com',['포켓캐스트'],'PC','stream','https://support.pocketcasts.com/knowledge-base/terms-of-use/','https://automattic.com/privacy/'],
    ['castbox','Castbox','castbox.fm',['캐스트박스'],'C','stream','https://castbox.fm/policy/terms.html','https://castbox.fm/policy/privacy.html'],
    ['qobuz','Qobuz','qobuz.com',['코부즈'],'Q','stream','https://www.qobuz.com/gb-en/legal/terms','https://www.qobuz.com/gb-en/legal/privacy'],
    ['bandcamp','Bandcamp','bandcamp.com',['밴드캠프'],'BC','stream','https://bandcamp.com/terms_of_use','https://bandcamp.com/privacy'],

    ['bestbuy','Best Buy','bestbuy.com',['베스트바이'],'BB','commerce','https://www.bestbuy.com/site/help-topics/terms-and-conditions/pcmcat204400050067.c','https://www.bestbuy.com/site/help-topics/privacy-policy/pcmcat204400050062.c'],
    ['homedepot','The Home Depot','homedepot.com',['홈디포'],'HD','commerce','https://www.homedepot.com/c/Terms_of_Use','https://www.homedepot.com/privacy/privacy-and-security-statement'],
    ['wayfair','Wayfair','wayfair.com',['웨이페어'],'W','commerce','https://www.wayfair.com/customerservice/general_info.php#terms','https://www.wayfair.com/customerservice/general_info.php#privacy'],
    ['wish','Wish','wish.com',['위시'],'W','commerce','https://www.wish.com/terms','https://www.wish.com/privacy_policy'],
    ['zalando','Zalando','zalando.com',['잘란도'],'Z','commerce','https://www.zalando.com/zalando-terms/','https://www.zalando.com/zalando-privacy-policy/'],
    ['asos','ASOS','asos.com',['에이소스'],'A','commerce','https://www.asos.com/terms-and-conditions/','https://www.asos.com/privacy-policy/'],
    ['farfetch','FARFETCH','farfetch.com',['파페치'],'F','commerce','https://www.farfetch.com/terms-and-conditions.aspx','https://www.farfetch.com/privacy-policy.aspx'],
    ['uniqlo','UNIQLO','uniqlo.com',['유니클로'],'U','commerce','https://www.uniqlo.com/us/en/terms-of-use.html','https://www.uniqlo.com/us/en/privacy-policy.html'],
    ['hm','H&M','hm.com',['에이치앤엠'],'H','commerce','https://www2.hm.com/en_us/customer-service/legal-and-privacy/terms-and-conditions.html','https://www2.hm.com/en_us/customer-service/legal-and-privacy/privacy-link.html'],
    ['ably','에이블리','a-bly.com',['ably'],'A','commerce','https://a-bly.com/terms','https://a-bly.com/privacy'],
    ['queenit','퀸잇','queenit.kr',['queenit'],'Q','commerce','https://www.queenit.kr/terms','https://www.queenit.kr/privacy'],
    ['karrot','당근','daangn.com',['당근마켓','karrot'],'당','commerce','https://www.daangn.com/policy/terms','https://www.daangn.com/policy/privacy'],
    ['bunjang','번개장터','bunjang.co.kr',['번장'],'번','commerce','https://terms.bunjang.co.kr/terms/service.html','https://terms.bunjang.co.kr/terms/privacy.html'],
    ['auction','옥션','auction.co.kr',['auction korea'],'옥','commerce','https://member.auction.co.kr/Authenticate/Agreement.aspx','https://member.auction.co.kr/Authenticate/PrivacyPolicy.aspx'],
    ['coupangeats','쿠팡이츠','coupangeats.com',['coupang eats'],'CE','commerce','https://www.coupangeats.com/terms','https://privacy.coupang.com/ko/center/coupang/'],
    ['doordash','DoorDash','doordash.com',['도어대시'],'DD','commerce','https://help.doordash.com/legal/document?type=dx-terms-and-conditions','https://help.doordash.com/legal/document?type=dx-privacy-policy'],
    ['instacart','Instacart','instacart.com',['인스타카트'],'I','commerce','https://www.instacart.com/terms','https://www.instacart.com/privacy'],
    ['deliveroo','Deliveroo','deliveroo.com',['딜리버루'],'D','commerce','https://deliveroo.co.uk/legal','https://deliveroo.co.uk/privacy'],
    ['foodpanda','foodpanda','foodpanda.com',['푸드판다'],'F','commerce','https://www.foodpanda.com/terms-and-conditions/','https://www.foodpanda.com/privacy-policy/'],
    ['ubereats','Uber Eats','ubereats.com',['우버이츠'],'UE','commerce','https://www.uber.com/legal/terms/','https://www.uber.com/legal/privacy/'],
    ['costco','Costco','costco.com',['코스트코'],'C','commerce','https://www.costco.com/terms-and-conditions-of-use.html','https://www.costco.com/privacy-policy.html'],
    ['macys','Macy’s','macys.com',['메이시스'],'M','commerce','https://www.macys.com/p/terms-of-use/','https://www.macys.com/p/privacy-policy/'],
    ['nordstrom','Nordstrom','nordstrom.com',['노드스트롬'],'N','commerce','https://www.nordstrom.com/browse/customer-service/policy/terms-conditions','https://www.nordstrom.com/browse/customer-service/policy/privacy'],
    ['iherb','iHerb','iherb.com',['아이허브'],'iH','commerce','https://www.iherb.com/info/terms-of-use','https://www.iherb.com/info/privacy'],
    ['samsungshop','Samsung Shop','samsung.com',['삼성닷컴','삼성샵'],'SS','commerce','https://www.samsung.com/us/common/terms-conditions/','https://www.samsung.com/us/account/privacy-policy/'],

    ['onedrive','OneDrive','onedrive.live.com',['원드라이브'],'OD','productivity','https://www.microsoft.com/servicesagreement','https://privacy.microsoft.com/privacystatement'],
    ['googleworkspace','Google Workspace','workspace.google.com',['구글워크스페이스'],'GW','productivity','https://workspace.google.com/terms/','https://policies.google.com/privacy'],
    ['gmail','Gmail','mail.google.com',['지메일'],'G','productivity','https://policies.google.com/terms','https://policies.google.com/privacy'],
    ['outlook','Outlook','outlook.live.com',['아웃룩'],'O','productivity','https://www.microsoft.com/servicesagreement','https://privacy.microsoft.com/privacystatement'],
    ['yahoomail','Yahoo Mail','mail.yahoo.com',['야후메일'],'Y','productivity','https://legal.yahoo.com/us/en/yahoo/terms/otos/index.html','https://legal.yahoo.com/us/en/yahoo/privacy/index.html'],
    ['protonmail','Proton Mail','proton.me',['프로톤메일'],'P','productivity','https://proton.me/legal/terms','https://proton.me/legal/privacy'],
    ['protondrive','Proton Drive','drive.proton.me',['프로톤드라이브'],'PD','productivity','https://proton.me/legal/terms','https://proton.me/legal/privacy'],
    ['wetransfer','WeTransfer','wetransfer.com',['위트랜스퍼'],'WT','productivity','https://wetransfer.com/terms','https://wetransfer.com/privacy'],
    ['mega','MEGA','mega.io',['메가클라우드'],'M','productivity','https://mega.io/terms','https://mega.io/privacy'],
    ['pcloud','pCloud','pcloud.com',['피클라우드'],'pC','productivity','https://www.pcloud.com/terms_and_conditions.html','https://www.pcloud.com/privacy_policy.html'],
    ['linear','Linear','linear.app',['리니어'],'L','productivity','https://linear.app/terms','https://linear.app/privacy'],
    ['airtable','Airtable','airtable.com',['에어테이블'],'A','productivity','https://www.airtable.com/company/terms','https://www.airtable.com/company/privacy'],
    ['basecamp','Basecamp','basecamp.com',['베이스캠프'],'B','productivity','https://basecamp.com/about/policies/terms','https://basecamp.com/about/policies/privacy'],
    ['smartsheet','Smartsheet','smartsheet.com',['스마트시트'],'S','productivity','https://www.smartsheet.com/legal/terms-of-use','https://www.smartsheet.com/legal/privacy'],
    ['wrike','Wrike','wrike.com',['라이크'],'W','productivity','https://www.wrike.com/security/terms/','https://www.wrike.com/security/privacy/'],
    ['zoho','Zoho','zoho.com',['조호'],'Z','productivity','https://www.zoho.com/terms.html','https://www.zoho.com/privacy.html'],
    ['hubspot','HubSpot','hubspot.com',['허브스팟'],'H','productivity','https://legal.hubspot.com/legal-stuff','https://legal.hubspot.com/privacy-policy'],
    ['salesforce','Salesforce','salesforce.com',['세일즈포스'],'SF','productivity','https://www.salesforce.com/company/legal/','https://www.salesforce.com/company/privacy/'],
    ['zendesk','Zendesk','zendesk.com',['젠데스크'],'Z','productivity','https://www.zendesk.com/company/agreements-and-terms/','https://www.zendesk.com/company/agreements-and-terms/privacy-notice/'],
    ['intercom','Intercom','intercom.com',['인터콤'],'I','productivity','https://www.intercom.com/legal/terms-and-policies','https://www.intercom.com/legal/privacy'],
    ['mailchimp','Mailchimp','mailchimp.com',['메일침프'],'M','productivity','https://mailchimp.com/legal/terms/','https://www.intuit.com/privacy/statement/'],
    ['typeform','Typeform','typeform.com',['타입폼'],'T','productivity','https://www.typeform.com/help/a/terms-and-conditions-360029581691/','https://admin.typeform.com/to/dwk6gt'],
    ['jotform','Jotform','jotform.com',['조트폼'],'J','productivity','https://www.jotform.com/terms/','https://www.jotform.com/privacy/'],
    ['surveymonkey','SurveyMonkey','surveymonkey.com',['서베이몽키'],'SM','productivity','https://www.surveymonkey.com/mp/legal/terms-of-use/','https://www.surveymonkey.com/mp/legal/privacy/'],
    ['loom','Loom','loom.com',['룸'],'L','productivity','https://www.loom.com/terms','https://www.loom.com/privacy-policy'],
    ['webex','Webex','webex.com',['웹엑스'],'W','productivity','https://www.cisco.com/c/en/us/about/legal/terms-conditions.html','https://www.cisco.com/c/en/us/about/legal/privacy-full.html'],
    ['teams','Microsoft Teams','teams.microsoft.com',['팀즈'],'T','productivity','https://www.microsoft.com/servicesagreement','https://privacy.microsoft.com/privacystatement'],
    ['googlemeet','Google Meet','meet.google.com',['구글미트'],'GM','productivity','https://policies.google.com/terms','https://policies.google.com/privacy'],
    ['obsidian','Obsidian','obsidian.md',['옵시디언'],'O','productivity','https://obsidian.md/terms','https://obsidian.md/privacy'],
    ['replit','Replit','replit.com',['리플릿'],'R','productivity','https://replit.com/site/terms','https://replit.com/site/privacy'],
    ['codesandbox','CodeSandbox','codesandbox.io',['코드샌드박스'],'CS','productivity','https://codesandbox.io/legal/terms','https://codesandbox.io/legal/privacy'],
    ['vercel','Vercel','vercel.com',['버셀'],'V','productivity','https://vercel.com/legal/terms','https://vercel.com/legal/privacy-policy'],
    ['netlify','Netlify','netlify.com',['넷리파이'],'N','productivity','https://www.netlify.com/legal/terms-of-use/','https://www.netlify.com/privacy/'],
    ['cloudflare','Cloudflare','cloudflare.com',['클라우드플레어'],'CF','productivity','https://www.cloudflare.com/terms/','https://www.cloudflare.com/privacypolicy/'],
    ['digitalocean','DigitalOcean','digitalocean.com',['디지털오션'],'DO','productivity','https://www.digitalocean.com/legal/terms-of-service-agreement','https://www.digitalocean.com/legal/privacy-policy'],

    ['googlemaps','Google Maps','maps.google.com',['구글지도'],'GM','travel','https://maps.google.com/help/terms_maps/','https://policies.google.com/privacy'],
    ['waze','Waze','waze.com',['웨이즈'],'W','travel','https://www.waze.com/legal/tos','https://www.waze.com/legal/privacy'],
    ['citymapper','Citymapper','citymapper.com',['시티매퍼'],'C','travel','https://citymapper.com/terms','https://citymapper.com/privacy'],
    ['moovit','Moovit','moovitapp.com',['무빗'],'M','travel','https://moovitapp.com/terms-of-service/','https://moovitapp.com/privacy-policy/'],
    ['lime','Lime','li.me',['라임킥보드'],'L','travel','https://www.li.me/user-agreement','https://www.li.me/privacy'],
    ['bird','Bird','bird.co',['버드킥보드'],'B','travel','https://www.bird.co/terms','https://www.bird.co/privacy'],
    ['getaround','Getaround','getaround.com',['겟어라운드'],'G','travel','https://www.getaround.com/terms','https://www.getaround.com/privacy'],
    ['sixt','SIXT','sixt.com',['식스트'],'S','travel','https://www.sixt.com/shared/t-c/','https://www.sixt.com/shared/privacy/'],
    ['hertz','Hertz','hertz.com',['허츠'],'H','travel','https://www.hertz.com/rentacar/navigation/templates/legalView.jsp','https://www.hertz.com/rentacar/privacypolicy/index.jsp'],
    ['avis','Avis','avis.com',['에이비스'],'A','travel','https://www.avis.com/en/legal-documents/terms-and-conditions','https://www.avis.com/en/privacy-notice'],
    ['rentalcars','Rentalcars.com','rentalcars.com',['렌탈카스'],'RC','travel','https://www.rentalcars.com/TermsAndConditions.do','https://www.rentalcars.com/PrivacyPolicy.do'],
    ['hopper','Hopper','hopper.com',['호퍼'],'H','travel','https://hopper.com/legal/terms','https://hopper.com/legal/privacy'],
    ['traveloka','Traveloka','traveloka.com',['트래블로카'],'T','travel','https://www.traveloka.com/en-id/termsandconditions','https://www.traveloka.com/en-id/privacynotice'],
    ['omio','Omio','omio.com',['오미오'],'O','travel','https://www.omio.com/terms-of-use','https://www.omio.com/privacy-policy'],
    ['trainline','Trainline','thetrainline.com',['트레인라인'],'T','travel','https://www.thetrainline.com/terms','https://www.thetrainline.com/terms/privacy'],

    ['paypal','PayPal','paypal.com',['페이팔'],'P','finance','https://www.paypal.com/us/legalhub/useragreement-full','https://www.paypal.com/us/legalhub/privacy-full'],
    ['venmo','Venmo','venmo.com',['벤모'],'V','finance','https://venmo.com/legal/us-user-agreement/','https://venmo.com/legal/us-privacy-policy/'],
    ['cashapp','Cash App','cash.app',['캐시앱'],'CA','finance','https://cash.app/legal/us/en-us/tos','https://cash.app/legal/us/en-us/privacy'],
    ['wise','Wise','wise.com',['와이즈'],'W','finance','https://wise.com/terms-of-use','https://wise.com/privacy-policy'],
    ['revolut','Revolut','revolut.com',['레볼루트'],'R','finance','https://www.revolut.com/legal/terms/','https://www.revolut.com/legal/privacy/'],
    ['coinbase','Coinbase','coinbase.com',['코인베이스'],'C','finance','https://www.coinbase.com/legal/user_agreement','https://www.coinbase.com/legal/privacy'],
    ['binance','Binance','binance.com',['바이낸스'],'B','finance','https://www.binance.com/en/terms','https://www.binance.com/en/privacy'],
    ['robinhood','Robinhood','robinhood.com',['로빈후드'],'R','finance','https://robinhood.com/us/en/about/legal/','https://robinhood.com/us/en/about/legal/privacy/'],
    ['tinder','Tinder','tinder.com',['틴더'],'T','dating','https://policies.tinder.com/terms','https://policies.tinder.com/privacy'],
    ['bumble','Bumble','bumble.com',['범블'],'B','dating','https://bumble.com/terms','https://bumble.com/privacy'],
    ['hinge','Hinge','hinge.co',['힌지'],'H','dating','https://hinge.co/terms','https://hinge.co/privacy'],
    ['okcupid','OkCupid','okcupid.com',['오케이큐피드'],'OK','dating','https://www.okcupid.com/legal/terms','https://www.okcupid.com/legal/privacy'],
    ['match','Match','match.com',['매치닷컴'],'M','dating','https://www.match.com/registration/membagr.aspx','https://www.match.com/registration/privacystatement.aspx'],
    ['strava','Strava','strava.com',['스트라바'],'S','health','https://www.strava.com/legal/terms','https://www.strava.com/legal/privacy'],
    ['fitbit','Fitbit','fitbit.com',['핏빗'],'F','health','https://www.fitbit.com/global/us/legal/terms-of-service','https://www.fitbit.com/global/us/legal/privacy-policy'],
    ['myfitnesspal','MyFitnessPal','myfitnesspal.com',['마이피트니스팔'],'MFP','health','https://www.myfitnesspal.com/terms-of-service','https://www.myfitnesspal.com/privacy-policy'],
    ['calm','Calm','calm.com',['캄','캄앱'],'C','health','https://www.calm.com/terms','https://www.calm.com/privacy-policy'],
    ['indeed','Indeed','indeed.com',['인디드'],'I','productivity','https://hrtechprivacy.com/brands/indeed/terms','https://hrtechprivacy.com/brands/indeed#privacypolicy'],
    ['glassdoor','Glassdoor','glassdoor.com',['글래스도어'],'G','productivity','https://www.glassdoor.com/about/terms/','https://www.glassdoor.com/about/privacy/'],
    ['upwork','Upwork','upwork.com',['업워크'],'U','commerce','https://www.upwork.com/legal#terms','https://www.upwork.com/legal#privacy'],
    ['fiverr','Fiverr','fiverr.com',['파이버'],'F','commerce','https://www.fiverr.com/legal-portal/legal-terms/terms-of-service','https://www.fiverr.com/legal-portal/legal-terms/privacy-policy'],
    ['khanacademy','Khan Academy','khanacademy.org',['칸아카데미'],'KA','learning','https://www.khanacademy.org/about/tos','https://www.khanacademy.org/about/privacy-policy'],
    ['edx','edX','edx.org',['이디엑스'],'edX','learning','https://www.edx.org/edx-terms-service','https://www.edx.org/edx-privacy-policy'],
    ['skillshare','Skillshare','skillshare.com',['스킬셰어'],'S','learning','https://www.skillshare.com/en/terms','https://www.skillshare.com/en/privacy'],
    ['codecademy','Codecademy','codecademy.com',['코드카데미'],'C','learning','https://www.codecademy.com/terms','https://www.codecademy.com/policy']
  ];

  return Object.fromEntries(catalog.map(([key,name,domain,aliases,mark,profile,source,privacy])=>{
    const p=profiles[profile];
    return [key,{name,domain,aliases,mark,profile,overall:p.overall,source,items:p.items(name,source,privacy)}];
  }));
})();
